"""empty message

Revision ID: 66ea6c4b686a
Revises: 398dcfccb545
Create Date: 2023-01-24 16:31:56.777177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ea6c4b686a'
down_revision = '398dcfccb545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('upcoming_shows')
        batch_op.drop_column('past_shows_count')
        batch_op.drop_column('upcoming_shows_count')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('upcoming_shows')
        batch_op.drop_column('past_shows_count')
        batch_op.drop_column('upcoming_shows_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('upcoming_shows', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('upcoming_shows', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
